POST http://localhost:8000/users
Content-Type: application/json

{
    "first_name": "Mark",
    "last_name": "Moawad",
    "username": "mowin99",
    "password": "123"
}

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "first_name": "Sherzod",
    "last_name": "Nim",
    "username": "mmvvpp123",
    "password": "123"
}


###

GET http://localhost:8000/users


###

GET http://localhost:8000/entries


###

POST http://localhost:8000/entries/10
Content-Type: application/json

{
    "title": "After Delete 2",
    "mood": "Hopeful",
    "entry": "Testing after delete for user 1"
}


###

PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "first_name": "Mark",
    "last_name": "Moawad",
    "username": "moawin99",
    "password": "123"
}

###

DELETE http://localhost:8000/users/9 