POST http://localhost:8000/users
Content-Type: application/json

{
    "first_name": "Mark",
    "last_name": "Moawad",
    "username": "mowin99",
    "password": "123"
}

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "first_name": "Sherzod",
    "last_name": "Nim",
    "username": "mmvvpp123",
    "password": "123"
}


###

GET http://localhost:8000/v1/users/test

###

GET http://localhost:8000/v1/users

###

GET http://localhost:8000/v1/users/me


###

GET http://localhost:8000/v1/entries/me


###

POST http://localhost:8000/v1/entries
Content-Type: application/json

{
    "title": "Testing auth 1",
    "mood": "Good",
    "entry": "Testing protected routes with auth"
}


###

PUT http://localhost:8000/v1/users
Content-Type: application/json

{
    "first_name": "Mark",
    "last_name": "Moawad",
    "username": "mowin99",
    "password": "123"
}

###

DELETE http://localhost:8000/v1/users

###

POST http://localhost:8000/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "mowin99",
    "password": "123"
}


###

POST http://localhost:8000/v1/users/logout

###

GET http://localhost:8000/v1/spotify/auth

###

GET http://localhost:8000/v1/spotify/playlists

###

POST http://localhost:8000/v1/spotify/tracks
Content-Type: application/json

{
    "playlistID": "1cwsDri454OF9HlhPLIf9z"
}

###

GET http://localhost:8000/v1/spotify/features
Content-Type: application/json


{
    "ids": [
        "7MAibcTli4IisCtbHKrGMh",
        "3AN70xkC9i9fFBpKlukRhY",
        "577g1tDBKntqev2lLDydxs"
        ]
}